name: CMake

on:
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      
    


jobs:

  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-13

    steps:
    - name: homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: ldid
      run: brew install ldid && brew install cmake && brew install wget

    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: get modified gd ipa (icrear development)
      run: wget https://cdn.discordapp.com/attachments/427893900594774026/1033766985831546940/qpxcytf.zip -P /Users/runner/work/enzyme/enzyme/example/ && unzip /Users/runner/work/enzyme/enzyme/example/qpxcytf.zip -d /Users/runner/work/enzyme/enzyme/example/ && wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake -P /Users/runner/work/enzyme/enzyme/example/
    - name: dont remember why
      run: mkdir build && cd build && mkdir enzyme_bin
    
    - name: python
      run: cd ../ && python -m pip install keystone && pip3 install capstone && pip3 install keystone-engine --upgrade
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cd example && cmake . -DCMAKE_TOOLCHAIN_FILE=/Users/runner/work/enzyme/enzyme/example/ios.toolchain.cmake -DPLATFORM=OS64 && cd ../


# Required as of cmake 2.8.10
# set (CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "Force unset of the deployment target for iOS" FORCE)


    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/example
    
    
    - uses: actions/upload-artifact@v3
      with:
       name: funny
       path: /Users/runner/work/enzyme/enzyme/example/GeometryJump.ipa
