name: CMake
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
    - name: homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: ldid
      run: brew install ldid && brew install cmake && brew install wget
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: get modified gd ipa (icrear development)
      run: wget https://cdn.discordapp.com/attachments/427893900594774026/1033766985831546940/qpxcytf.zip -P /Users/runner/work/enzyme/enzyme/example/ && unzip /Users/runner/work/enzyme/enzyme/example/qpxcytf.zip -d /Users/runner/work/enzyme/enzyme/example/ && wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake -P /Users/runner/work/enzyme/enzyme/example/
    - name: dont remember why
      run: mkdir build && cd build && mkdir enzyme_bin
    - name: python
      run: cd ../ && python -m pip install keystone && pip3 install capstone && pip3 install keystone-engine --upgrade
    - name: Configure CMake
      run: cd example && cmake . -DCMAKE_TOOLCHAIN_FILE=/Users/runner/work/enzyme/enzyme/example/ios.toolchain.cmake -DPLATFORM=OS64 && cd ../
    - name: Build
      run: cmake --build ${{github.workspace}}/example
    - uses: actions/upload-artifact@v3
      with:
       name: funny
       path: /Users/runner/work/enzyme/enzyme/example/GeometryJump.ipa
